
package controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentServiceImpl", targetNamespace = "http://impl.service.soap.api.fiche.e20150907/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isValid", targetNamespace = "http://impl.service.soap.api.fiche.e20150907/", className = "controller.IsValid")
    @ResponseWrapper(localName = "isValidResponse", targetNamespace = "http://impl.service.soap.api.fiche.e20150907/", className = "controller.IsValidResponse")
    @Action(input = "http://impl.service.soap.api.fiche.e20150907/PaymentServiceImpl/isValidRequest", output = "http://impl.service.soap.api.fiche.e20150907/PaymentServiceImpl/isValidResponse")
    public boolean isValid(
        @WebParam(name = "arg0", targetNamespace = "")
        PaymentItem arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
