
package controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentServiceImplService", targetNamespace = "http://impl.service.soap.api.fiche.e20150907/", wsdlLocation = "http://localhost:8090/Payment?wsdl")
public class PaymentServiceImplService
    extends Service
{

    private final static URL PAYMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PAYMENTSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.soap.api.fiche.e20150907/", "PaymentServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/Payment?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PAYMENTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PaymentServiceImplService() {
        super(__getWsdlLocation(), PAYMENTSERVICEIMPLSERVICE_QNAME);
    }

    public PaymentServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public PaymentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSERVICEIMPLSERVICE_QNAME);
    }

    public PaymentServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public PaymentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentServiceImpl
     */
    @WebEndpoint(name = "PaymentServiceImplPort")
    public PaymentServiceImpl getPaymentServiceImplPort() {
        return super.getPort(new QName("http://impl.service.soap.api.fiche.e20150907/", "PaymentServiceImplPort"), PaymentServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentServiceImpl
     */
    @WebEndpoint(name = "PaymentServiceImplPort")
    public PaymentServiceImpl getPaymentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.soap.api.fiche.e20150907/", "PaymentServiceImplPort"), PaymentServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PAYMENTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PAYMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
